USE [JEDCMobility]
GO

CREATE TABLE [dbo].[Point] (
    [Id] INT PRIMARY KEY IDENTITY(1,1),
	[Date] DATE NOT NULL,
	[Time] VARCHAR(MAX) NOT NULL,--TIME NOT NULL,
	[DeviceId] VARCHAR(MAX) NOT NULL,
	[IdType] VARCHAR(MAX) NOT NULL,
	[Latitude] VARCHAR(MAX) NOT NULL,--DECIMAL(8,4) NOT NULL,
	[Longitude] VARCHAR(MAX) NOT NULL,--DECIMAL(8,4) NOT NULL,
	[HorizontalAccuracy] VARCHAR(MAX) NOT NULL,--DECIMAL(4,2) NOT NULL,
	[IpAddress] VARCHAR(16) NOT NULL,
	[DeviceOS] VARCHAR(MAX) NOT NULL,
	[OSVersion] VARCHAR(4) NOT NULL,
	[UserAgent] VARCHAR(MAX) NOT NULL,
	[Country] VARCHAR(2) NOT NULL,
	[SourceId] VARCHAR(MAX) NOT NULL,
	[PublisherId] VARCHAR(MAX) NOT NULL,
	[AppId] VARCHAR(MAX) NOT NULL,
	[LocationContext] VARCHAR(MAX) NOT NULL,
	[Geohash] VARCHAR(MAX) NOT NULL,
	[Consent] VARCHAR(4) NOT NULL,
	[QuadId] VARCHAR(MAX) NOT NULL,
)


--DROP TABLE [dbo].[Point] 